-- ============================================================
-- SOMA ARCHIVE — Supabase schema
-- Run this in the Supabase SQL editor (Dashboard > SQL Editor).
-- ============================================================

-- Collections: groupings you reorganize over time (e.g. "Tuscany 2026",
-- "Ornamental stone", "Encountered at fairs"). An artwork can belong to one.
create table if not exists collections (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  description text,
  sort_order  int default 0,
  created_at  timestamptz default now()
);

-- Artworks: the core record.
create table if not exists artworks (
  id            uuid primary key default gen_random_uuid(),
  title         text not null,
  artist        text,
  year          text,            -- text, not int: handles "c. 1610", "n.d.", ranges
  medium        text,
  dimensions    text,
  location      text,            -- where YOU encountered it (free text place name)
  latitude      double precision, -- auto from photo EXIF GPS, device geolocation, or manual
  longitude     double precision,
  notes         text,            -- your own observations
  ai_description text,           -- generated by the enrich endpoint
  ai_links      jsonb default '[]'::jsonb,  -- [{label, url}]
  sources       jsonb default '[]'::jsonb,  -- bibliography: [{citation, url}]
  tags          text[] default '{}',
  image_path    text,            -- cover / primary artwork photo (path in storage)
  card_image_path text,          -- the name/label card photo, if one was matched
  images        jsonb default '[]'::jsonb,  -- all photo paths for this work: ["path1","path2"]
  collection_id uuid references collections(id) on delete set null,
  sort_order    int default 0,   -- position within its collection
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- Full-text search vector, kept in sync by a trigger.
alter table artworks add column if not exists fts tsvector
  generated always as (
    to_tsvector('english'::regconfig,
      coalesce(title,'') || ' ' ||
      coalesce(artist,'') || ' ' ||
      coalesce(medium,'') || ' ' ||
      coalesce(location,'') || ' ' ||
      coalesce(notes,'') || ' ' ||
      coalesce(ai_description,'') || ' ' ||
      coalesce(array_to_string(tags,' '),'')
    )
  ) stored;

create index if not exists artworks_fts_idx on artworks using gin (fts);
create index if not exists artworks_tags_idx on artworks using gin (tags);
create index if not exists artworks_collection_idx on artworks (collection_id);
create index if not exists artworks_geo_idx on artworks (latitude, longitude);

-- Links between works: a cast of an original, a study for a piece, an influence, etc.
create table if not exists relationships (
  id        uuid primary key default gen_random_uuid(),
  from_id   uuid references artworks(id) on delete cascade,
  to_id     uuid references artworks(id) on delete cascade,
  kind      text not null default 'related',  -- related | cast_of | study_for | influenced_by | part_of
  created_at timestamptz default now(),
  unique (from_id, to_id, kind)
);
create index if not exists rel_from_idx on relationships (from_id);
create index if not exists rel_to_idx on relationships (to_id);

-- If you already ran an earlier version of this schema, add the new columns/tables:
--   alter table artworks add column if not exists latitude  double precision;
--   alter table artworks add column if not exists longitude double precision;
--   alter table artworks add column if not exists card_image_path text;
--   alter table artworks add column if not exists images jsonb default '[]'::jsonb;
--   alter table artworks add column if not exists sources jsonb default '[]'::jsonb;
--   (and run the relationships create table above)

-- keep updated_at fresh
create or replace function touch_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

drop trigger if exists artworks_touch on artworks;
create trigger artworks_touch before update on artworks
  for each row execute function touch_updated_at();

-- ============================================================
-- Storage bucket for images. Run once.
-- ============================================================
insert into storage.buckets (id, name, public)
values ('artwork-images', 'artwork-images', true)
on conflict (id) do nothing;

-- ============================================================
-- Row Level Security
-- Private to signed-in users. Since this is a single-user archive (you),
-- "any authenticated user" is enough to keep it private once Auth is on.
-- To make it multi-user later, add a user_id column and scope to auth.uid().
-- ============================================================
alter table artworks enable row level security;
alter table collections enable row level security;
alter table relationships enable row level security;

drop policy if exists artworks_all on artworks;
create policy artworks_all on artworks for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists collections_all on collections;
create policy collections_all on collections for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists relationships_all on relationships;
create policy relationships_all on relationships for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- storage policies — readable + writable by signed-in users
drop policy if exists "public read" on storage.objects;
create policy "auth read" on storage.objects
  for select using (bucket_id = 'artwork-images' and auth.role() = 'authenticated');

drop policy if exists "anon write" on storage.objects;
create policy "auth write" on storage.objects
  for insert with check (bucket_id = 'artwork-images' and auth.role() = 'authenticated');

drop policy if exists "anon update" on storage.objects;
create policy "auth update" on storage.objects
  for update using (bucket_id = 'artwork-images' and auth.role() = 'authenticated');

drop policy if exists "anon delete" on storage.objects;
create policy "auth delete" on storage.objects
  for delete using (bucket_id = 'artwork-images' and auth.role() = 'authenticated');
